In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

Importing two Datasets and Merging together

In [3]:
df = pd.read_csv("IPLData.csv")
df_2025 = pd.read_csv("IPL25.csv")
df_2025 = df_2025.rename(columns={
    'match_id': 'id',
    'match_winner': 'winner',
    'player_of_the_match': 'player_of_match'
})
df_2025 = df_2025[[
    'id', 'date', 'venue', 'team1', 'team2',
    'toss_winner', 'toss_decision', 'winner',
    'player_of_match'
]]
missing_cols = set(df.columns) - set(df_2025.columns)

for col in missing_cols:
    df_2025[col] = None
    
df_2025 = df_2025[df.columns]

df_final = pd.concat([df, df_2025], ignore_index=True)
df_final

/var/folders/ns/vvfqzp455wxblcv6pv14k9k40000gn/T/ipykernel_8037/2539038682.py:20: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_final = pd.concat([df, df_2025], ignore_index=True)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2008,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2008,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2008,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2008,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2008,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1164,70,None,None,"May 27,2025",None,Jitesh Sharma,"Ekana Cricket Stadium, Lucknow",LSG,RCB,RCB,Bowl,RCB,None,NaN,NaN,NaN,None,None,None,None
1165,71,None,None,"May 29,2025",None,Suyash Sharma,"New PCA Cricket Stadium, Mullanpur",PBKS,RCB,RCB,Bowl,RCB,None,NaN,NaN,NaN,None,None,None,None
1166,72,None,None,"May 30,2025",None,Rohit Sharma,"New PCA Cricket Stadium, Mullanpur",GT,MI,MI,Bat,MI,None,NaN,NaN,NaN,None,None,None,None
1167,73,None,None,"June 1,2025",None,Shreyas Iyer,"Narendra Modi Stadium, Ahmedabad",PBKS,MI,PBKS,Bowl,PBKS,None,NaN,NaN,NaN,None,None,None,None
1168,74,None,None,"June 3,2025",None,Krunal Pandya,"Narendra Modi Stadium, Ahmedabad",RCB,PBKS,PBKS,Bowl,RCB,None,NaN,NaN,NaN,None,None,None,None

Fixing team names by Mapping

In [4]:
print(df_2025['team1'].unique())

['KKR' 'SRH' 'CSK' 'DC' 'GT' 'RR' 'MI' 'LSG' 'RCB' 'PBKS']

In [5]:
team_map = {
    "MI": "Mumbai Indians",
    "CSK": "Chennai Super Kings",
    "RCB": "Royal Challengers Bangalore",
    "KKR": "Kolkata Knight Riders",
    "SRH": "Sunrisers Hyderabad",
    "DC": "Delhi Capitals",
    "RR": "Rajasthan Royals",
    "PBKS": "Kings XI Punjab",   
    "GT": "Gujarat Titans",
    "LSG": "Lucknow Super Giants"
}

df_2025['team1'] = df_2025['team1'].map(team_map)
df_2025['team2'] = df_2025['team2'].map(team_map)
df_2025['winner'] = df_2025['winner'].map(team_map)
df_2025['toss_winner'] = df_2025['toss_winner'].map(team_map)
print(df_2025[['team1','team2','winner']].head())

                   team1                        team2  \
0  Kolkata Knight Riders  Royal Challengers Bangalore
1    Sunrisers Hyderabad             Rajasthan Royals
2    Chennai Super Kings               Mumbai Indians
3         Delhi Capitals         Lucknow Super Giants
4         Gujarat Titans              Kings XI Punjab

                        winner
0  Royal Challengers Bangalore
1          Sunrisers Hyderabad
2          Chennai Super Kings
3               Delhi Capitals
4              Kings XI Punjab

Fixing names

In [14]:
player_map = {
    "V Kohli": "Virat Kohli",
    "RG Sharma": "Rohit Sharma",
    "DA Warner": "David Warner",
    "AD Russell": "Andre Russell",
    "CH Gayle": "Chris Gayle"
}
top_old = df['player_of_match'].value_counts().head(20)
df['player_of_match'] = df['player_of_match'].replace(player_map)
df['date'] = pd.to_datetime(df['date'])
df_2025['date'] = pd.to_datetime(df_2025['date'], format='%B %d,%Y')
df_final = pd.concat([df, df_2025], ignore_index=True)
df_final

/var/folders/ns/vvfqzp455wxblcv6pv14k9k40000gn/T/ipykernel_8037/4124130983.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_final = pd.concat([df, df_2025], ignore_index=True)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2008,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2008,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2008,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2008,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2008,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1164,70,None,None,2025-05-27,None,Jitesh Sharma,"Ekana Cricket Stadium, Lucknow",Lucknow Super Giants,Royal Challengers Bangalore,Royal Challengers Bangalore,Bowl,Royal Challengers Bangalore,None,NaN,NaN,NaN,None,None,None,None
1165,71,None,None,2025-05-29,None,Suyash Sharma,"New PCA Cricket Stadium, Mullanpur",Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,Bowl,Royal Challengers Bangalore,None,NaN,NaN,NaN,None,None,None,None
1166,72,None,None,2025-05-30,None,Rohit Sharma,"New PCA Cricket Stadium, Mullanpur",Gujarat Titans,Mumbai Indians,Mumbai Indians,Bat,Mumbai Indians,None,NaN,NaN,NaN,None,None,None,None
1167,73,None,None,2025-06-01,None,Shreyas Iyer,"Narendra Modi Stadium, Ahmedabad",Kings XI Punjab,Mumbai Indians,Kings XI Punjab,Bowl,Kings XI Punjab,None,NaN,NaN,NaN,None,None,None,None
1168,74,None,None,2025-06-03,None,Krunal Pandya,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,Bowl,Royal Challengers Bangalore,None,NaN,NaN,NaN,None,None,None,None

In [15]:
df_final.to_csv("ipl_cleaned.csv", index=False)